### ISSUE TITLE
CPU Speed?

### ISSUE THREAD

**Issue by LeeKyungwook** [micaelillos/Mask-Detection#1]
Thanks for opening great mask detection code.
I have a question.
When I run your model on cpu, speed is 25~35ms. I think this is too slow because your model used mobilenet.
Is this speed correct?

**Comment by micaelillos** [comment]
Thanks to the A12's amazing Neural Engine, Core ML achieves almost unbelievable speeds. MobileNet V1 and MobileNet V2 easily run at over 240 FPS — and if you really push it you can get them up to 600 FPS!
The speed also depends on your computer's specifications, it's probably slow because your pc is junk, please try to open issues that are actually relevant thanks
